apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "postgres"
  JWT_VERIFY_SECRET: "L6xOeIB5b1X7CnkXGRpCvaAJvFbHvS3a"
  JWT_SESSION_SECRET: "uGXbqsLwLb4gsGcqgtFgcrT3TGRMjchZ"
  SESSION_ENCRYPT_SECRET: "7EwNLyb6QQX7Mr0B7EwNLyb6QQX7Mr0B"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "react_auth_db"
